import type { Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { UserSyncProvider } from '@/components/auth/UserSyncProvider'
import {
  NavigationMenu,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
  navigationMenuTriggerStyle,
} from "@/components/ui/navigation-menu"
import Link from "next/link"
import { ThemeProvider } from "@/components/theme-provider"
import { ModeToggle } from '@/components/ui/mode-toggle'
import { ShoppingCart } from 'lucide-react';
import { Button } from '@/components/ui/button'



const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <UserSyncProvider>
              <header className="fixed top-0 left-0 right-0 z-50 flex justify-between items-center p-4 h-16 bg-white/80 dark:bg-background/80 backdrop-blur-md border-b border-border">
                <div className="flex items-center">
                  <div className="flex items-center gap-2">
                    <svg
                      width="32"
                      height="32"
                      viewBox="0 0 32 32"
                      className="fill-[#6c47ff] dark:fill-[#8b5cf6]"
                    >
                      <path d="M6 8a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a6 6 0 0 1-6 6H8a6 6 0 0 1-6-6V8z" />
                      <path d="M22 10h2a4 4 0 0 1 4 4v2a4 4 0 0 1-4 4h-2" className="fill-[#6c47ff]/70 dark:fill-[#8b5cf6]/70" />
                      <circle cx="10" cy="12" r="1" className="fill-white dark:fill-gray-900" />
                      <circle cx="14" cy="12" r="1" className="fill-white dark:fill-gray-900" />
                      <path d="M9 16a3 3 0 0 0 6 0" stroke="white" strokeWidth="1.5" fill="none" className="stroke-white dark:stroke-gray-900" />
                    </svg>
                    <div className="text-xl font-bold text-[#6c47ff] dark:text-[#8b5cf6]">
                      Cafee
                    </div>
                  </div>
                </div>

                <div className="flex justify-center">
                  <NavigationMenu>
                    <NavigationMenuList>
                      <NavigationMenuItem>
                        <NavigationMenuLink asChild className={navigationMenuTriggerStyle()}>
                          <Link href="/">Home</Link>
                        </NavigationMenuLink>
                      </NavigationMenuItem>
                      <NavigationMenuItem>
                        <NavigationMenuLink asChild className={navigationMenuTriggerStyle()}>
                          <Link href="/menu">Menu</Link>
                        </NavigationMenuLink>
                      </NavigationMenuItem>
                      <NavigationMenuItem>
                        <NavigationMenuLink asChild className={navigationMenuTriggerStyle()}>
                          <Link href="/docs">About</Link>
                        </NavigationMenuLink>
                      </NavigationMenuItem>
                      <NavigationMenuItem>
                        <NavigationMenuLink asChild className={navigationMenuTriggerStyle()}>
                          <Link href="/docs">Galery</Link>
                        </NavigationMenuLink>
                      </NavigationMenuItem>
                    </NavigationMenuList>
                  </NavigationMenu>
                </div>

                <div className="flex items-center gap-4">
                  <Link href="/cart" passHref>
                    <Button variant="outline" size="icon">
                      <ShoppingCart />
                    </Button>
                  </Link>
                  <ModeToggle />
                  <SignedOut>
                    <SignInButton />
                    <SignUpButton>
                      <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                        Sign Up
                      </button>
                    </SignUpButton>
                  </SignedOut>
                  <SignedIn>
                    <UserButton />
                  </SignedIn>
                </div>
              </header>
              <main className="pt-16">
                {children}
              </main>
            </UserSyncProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}